// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfc3jlGSAoL08KaDVVXS7s481l158GbKc',
    appId: '1:1017048356584:android:c6792614ac291a6cf7db5d',
    messagingSenderId: '1017048356584',
    projectId: 'whatsapp-11d0d',
    storageBucket: 'whatsapp-11d0d.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNN-xZgEXbkV2oC9YFwk6-Gp5d9bIm1MU',
    appId: '1:1017048356584:web:d677a9d9d1022349f7db5d',
    messagingSenderId: '1017048356584',
    projectId: 'whatsapp-11d0d',
    authDomain: 'whatsapp-11d0d.firebaseapp.com',
    storageBucket: 'whatsapp-11d0d.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByngS2ZgU-LBOppSO5qq-C2gE1LIxh7QY',
    appId: '1:1017048356584:ios:d94fe5ab123c304df7db5d',
    messagingSenderId: '1017048356584',
    projectId: 'whatsapp-11d0d',
    storageBucket: 'whatsapp-11d0d.appspot.com',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByngS2ZgU-LBOppSO5qq-C2gE1LIxh7QY',
    appId: '1:1017048356584:ios:d94fe5ab123c304df7db5d',
    messagingSenderId: '1017048356584',
    projectId: 'whatsapp-11d0d',
    storageBucket: 'whatsapp-11d0d.appspot.com',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNN-xZgEXbkV2oC9YFwk6-Gp5d9bIm1MU',
    appId: '1:1017048356584:web:b985976a6f5a09b7f7db5d',
    messagingSenderId: '1017048356584',
    projectId: 'whatsapp-11d0d',
    authDomain: 'whatsapp-11d0d.firebaseapp.com',
    storageBucket: 'whatsapp-11d0d.appspot.com',
  );

}